version: '3'

networks:
  backend:
    
services:
  postgres:
    image: postgres
    container_name: pg-docker
    networks:
      backend:
        aliases: 
          - database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
  api:
    depends_on: 
      - postgres
    image: storysquad/tricktionary-api
    container_name: trixie
    networks: 
      - backend
    environment:
      - DATABASE_URL=postgresql://storysquad:llama@database:5432/tricktionary
    ports:
      - "5000:5000"
    restart: always
  web:
    depends_on: 
      - api
    image: storysquad/web
    ports:
    - "80:80"
    volumes:
      - ../tricktionary-fe/build:/usr/share/nginx/html
    networks: 
      - backend
    environment:
    - NGINX_PORT=80
    - REACT_APP_API_URL=http://0.0.0.0/api
    restart: always
