branch-defaults:
  main:
    environment: tricktionary-prod-env
    group_suffix: null
  production:
    environment: tricktionary-prod-env
global:
  application_name: tricktionary-prod
  branch: null
  default_ec2_keyname: tricktionary-keypair
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
