version: '3'
networks:
  backend:
services:
  postgres:
    image: postgres
    container_name: pg-docker
    networks:
      backend:
        aliases: 
          - database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
      - ../../postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - '6379:6379'
    networks:
      backend:
        aliases: 
          - redis